controllers:
    resource: ../src/Controller/
    type: attribute

# config/routes.yaml
returnRoles:
  path: /user/register
  methods: [GET]
  controller: App\Controller\RoleController::returnRoles

register:
  path: /user/register
  methods: [POST]
  controller: App\Controller\UserController::register
